/** @type {import('next').NextConfig} */
// transpilePackages は package.json の @platform/* 依存と一致させる。
// 手で並べると必ず漏れる(実際 task/contract/faq/blog/security/utils/cron が漏れていた)ので、
// tools/check-showcase-deps.mjs で機械的に検査する。
export default {
  transpilePackages: [
    "@platform/accounting",
    "@platform/address",
    "@platform/auth",
    "@platform/blog",
    "@platform/blueprint",
    "@platform/bluetooth",
    "@platform/board",
    "@platform/booking",
    "@platform/cast",
    "@platform/chat",
    "@platform/contract",
    "@platform/core",
    "@platform/cron",
    "@platform/crypto",
    "@platform/csv",
    "@platform/datetime",
    "@platform/device",
    "@platform/faq",
    "@platform/form",
    "@platform/freee",
    "@platform/guard",
    "@platform/hid",
    "@platform/http",
    "@platform/i18n",
    "@platform/image",
    "@platform/loadtest",
    "@platform/mail",
    "@platform/notify",
    "@platform/ocr",
    "@platform/payroll",
    "@platform/pdf",
    "@platform/print",
    "@platform/ratelimit",
    "@platform/realtime",
    "@platform/report",
    "@platform/security",
    "@platform/seo",
    "@platform/session",
    "@platform/social",
    "@platform/storage",
    "@platform/task",
    "@platform/theme",
    "@platform/ui",
    "@platform/upload",
    "@platform/utils",
    "@platform/validation",
    "@platform/workflow",
    "@platform/xlsx",
  ],
};
