import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** @type {import('next').NextConfig} */
export default {
  // Turbopack の root はモノレポのルート。
  // 指定しないと root を推測して cwd とずれ、node_modules を解決できない。
  // pnpm は node_modules をルートに集約するので、ここを指す必要がある。
  turbopack: {
    root: path.join(__dirname, "../.."),
  },

  // 基盤パッケージは **ソースを直接読む**(package.json の main が src/index.ts)。
  // ここに列挙したものが TS のままバンドルされる。
  //
  // package.json の @platform/* 依存と一致させること。手で並べると必ず漏れるので、
  // tools/check-showcase-deps.mjs で機械的に検査する。
  transpilePackages: [
    "@platform/accounting",
    "@platform/address",
    "@platform/analytics",
    "@platform/apikey",
    "@platform/ai",
    "@platform/auth",
    "@platform/barcode",
    "@platform/attendance",
    "@platform/audit",
    "@platform/blog",
    "@platform/blueprint",
    "@platform/bluetooth",
    "@platform/board",
    "@platform/booking",
    "@platform/cast",
    "@platform/chat",
    "@platform/cms",
    "@platform/commerce",
    "@platform/contract",
    "@platform/core",
    "@platform/cron",
    "@platform/crypto",
    "@platform/csv",
    "@platform/currency",
    "@platform/datetime",
    "@platform/dencho",
    "@platform/ekyc",
    "@platform/depreciation",
    "@platform/device",
    "@platform/elearning",
    "@platform/faq",
    "@platform/flags",
    "@platform/form",
    "@platform/freee",
    "@platform/fsm",
    "@platform/google",
    "@platform/guard",
    "@platform/hid",
    "@platform/http",
    "@platform/html",
    "@platform/i18n",
    "@platform/image",
    "@platform/importer",
    "@platform/invoice",
    "@platform/line",
    "@platform/inventory",
    "@platform/loadtest",
    "@platform/mcp",
    "@platform/mobile",
    "@platform/mail",
    "@platform/notify",
    "@platform/observability",
    "@platform/ocr",
    "@platform/payroll",
    "@platform/pdf",
    "@platform/phone",
    "@platform/pii",
    "@platform/print",
    "@platform/purchase",
    "@platform/rag",
    "@platform/env",
    "@platform/faker",
    "@platform/net",
    "@platform/microsoft",
    "@platform/notion",
    "@platform/slack",
    "@platform/rpa",
    "@platform/ratelimit",
    "@platform/quote",
    "@platform/realtime",
    "@platform/report",
    "@platform/search",
    "@platform/secrets",
    "@platform/saga",
    "@platform/security",
    "@platform/sequence",
    "@platform/site",
    "@platform/seo",
    "@platform/session",
    "@platform/social",
    "@platform/status-page",
    "@platform/storage",
    "@platform/task",
    "@platform/tax",
    "@platform/theme",
    "@platform/ui",
    "@platform/units",
    "@platform/upload",
    "@platform/url",
    "@platform/utils",
    "@platform/validation",
    "@platform/workflow",
    "@platform/xlsx",
    "@platform/zoho",
    "@platform/zengin",
  ],
};
