import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** @type {import('next').NextConfig} */
export default {
  // **開発時に副作用のバグを見つける。**
  // 効果を 2 回実行して、後始末を書き忘れた処理を炙り出す
  // (本番の動きは変わらない)。他のアプリと揃える
  reactStrictMode: true,
  // **Next 15 の `next build` は webpack。** monorepo では基点を明示しないと
  // 推測に頼り、**必要なファイルが成果物に入らない**ことがある。
  outputFileTracingRoot: path.join(__dirname, "../.."),
  // Turbopack の root はモノレポのルート。
  // 指定しないと root を推測して cwd とずれ、node_modules を解決できない。
  // pnpm は node_modules をルートに集約するので、ここを指す必要がある。
  turbopack: {
    root: path.join(__dirname, "../.."),
  },

  // 基盤パッケージは **ソースを直接読む**(package.json の main が src/index.ts)。
  // ここに列挙したものが TS のままバンドルされる。
  //
  // package.json の @platform/* 依存と一致させること。手で並べると必ず漏れるので、
  // tools/check-showcase-deps.mjs で機械的に検査する。
  transpilePackages: [
    "@platform/access-review",
    "@platform/accounting",
    "@platform/address",
    "@platform/ai",
    "@platform/analytics",
    "@platform/apikey",
    "@platform/attendance",
    "@platform/audit",
    "@platform/auth",
    "@platform/barcode",
    "@platform/blog",
    "@platform/blueprint",
    "@platform/bluetooth",
    "@platform/board",
    "@platform/booking",
    "@platform/cast",
    "@platform/chat",
    "@platform/cms",
    "@platform/commerce",
    "@platform/contract",
    "@platform/core",
    "@platform/cron",
    "@platform/crypto",
    "@platform/csv",
    "@platform/currency",
    "@platform/datetime",
    "@platform/dencho",
    "@platform/depreciation",
    "@platform/device",
    "@platform/ekyc",
    "@platform/elearning",
    "@platform/env",
    "@platform/faker",
    "@platform/faq",
    "@platform/flags",
    "@platform/form",
    "@platform/freee",
    "@platform/fs",
    "@platform/fsm",
    "@platform/google",
    "@platform/guard",
    "@platform/hid",
    "@platform/html",
    "@platform/http",
    "@platform/i18n",
    "@platform/image",
    "@platform/importer",
    "@platform/inventory",
    "@platform/invoice",
    "@platform/jobs",
    "@platform/line",
    "@platform/loadtest",
    "@platform/mail",
    "@platform/mcp",
    "@platform/media",
    "@platform/microsoft",
    "@platform/mobile",
    "@platform/net",
    "@platform/notify",
    "@platform/notion",
    "@platform/observability",
    "@platform/ocr",
    "@platform/paypal",
    "@platform/payroll",
    "@platform/pdf",
    "@platform/phone",
    "@platform/pii",
    "@platform/print",
    "@platform/purchase",
    "@platform/quote",
    "@platform/rag",
    "@platform/ratelimit",
    "@platform/realtime",
    "@platform/report",
    "@platform/rpa",
    "@platform/saga",
    "@platform/search",
    "@platform/secrets",
    "@platform/security",
    "@platform/seo",
    "@platform/sequence",
    "@platform/session",
    "@platform/site",
    "@platform/slack",
    "@platform/sms",
    "@platform/social",
    "@platform/status-page",
    "@platform/storage",
    "@platform/task",
    "@platform/tax",
    "@platform/theme",
    "@platform/ui",
    "@platform/units",
    "@platform/upload",
    "@platform/url",
    "@platform/utils",
    "@platform/validation",
    "@platform/webhook",
    "@platform/workflow",
    "@platform/xlsx",
    "@platform/xml",
    "@platform/zengin",
    "@platform/zoho",
  
    "@platform/bytes",
    "@platform/color",
    "@platform/json",
    "@platform/web-storage",],
};
